apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amq-streams-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/streams/overlays
    repoURL: https://github.com/naveenkendyala/gitops-demo
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true